app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

gestordepedidos/urls.py
from django.urls import path
from . import views

#Generic
urlpatterns = [
    path('home/', views.index, name='home'),
]


#Cliente
urlpatterns += [
    path('cliente/', views.listaCliente.as_view(), name='Cliente'),
    path('cliente/add', views.cadastroCliente, name='ClienteCadastro'),
    path('cliente/<int:pk>', views.detalhesCliente.as_view(), name='ClienteDetalhes'),
    path('cliente/edit/<int:pk>', views.editarCliente, name='ClienteEditar'),
    path('cliente/delete<int:pk>', views.excluirCliente, name='ClienteExcluir'),
]

#Item
urlpatterns += [
    path('item/', views.listaItem.as_view(), name='Item'),
    path('item/add', views.cadastroItem, name='ItemCadastro'),
    path('item/edit/<int:pk>', views.editarItem, name='ItemEditar'),
    path('item/delete<int:pk>', views.excluirItem, name='ItemExcluir'),
]

#Pedido
urlpatterns += [
    path('pedido/', views.listaPedido.as_view(), name='Pedido'),
    path('pedido/add', views.buscaCliente, name='ProcuraCliente'),
    path('pedido/add/<int:pk>', views.cadastroPedido, name='PedidoCadastro'),
    path('pedido/<int:pk>', views.detalhesPedido, name='PedidoDetalhes'),
    path('pedido/delete<int:pk>', views.excluirPedido, name='PedidoExcluir'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('', include('gestordepedidos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

gestordepedidos/models.py
from django.db import models

# Create your models here.

CATEGORIA_CHOICES = (
    ('Expediente','Expediente'),
    ('Mercearia','Mercearia'),
    ('Bebidas','Bebidas'),
    ('Alimento Não Perecível', 'Alimento Não Perecível'),
    ('Remédio', 'Remédio'),
    ('Protetor Solar', 'Protetor Solar')
)

class Cliente(models.Model):
    nome = models.CharField(max_length=96, blank = True, null = True)
    cpf = models.CharField(max_length=24, blank = True, null = True)
    email = models.EmailField(blank = True, null = True)

    def __str__(self):
        return self.nome

class Item(models.Model):
    descricao = models.CharField(max_length=100, blank = True, null = True)
    categoria = models.CharField(choices=CATEGORIA_CHOICES, max_length=50, blank = True, null = True)

    def __str__(self):
        return self.descricao

class Pedido(models.Model):
    idCliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, blank = True, null = True)
    data = models.DateTimeField(auto_now_add=True, blank = True, null = True)
    observacao = models.TextField(max_length=96, blank = True, null = True)

    def __str__(self):
        return str("Pedido " + str({self.pk}))

class ItensPedido(models.Model):
    pedidos = models.ForeignKey(Pedido, on_delete=models.CASCADE, blank = True, null = True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank = True, null = True)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.item.descricao

gestordepedidos/forms.py
from django import forms
from .models import *

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = "__all__"

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__"

class ItensPedidoForm(forms.ModelForm):
    class Meta:
        model = ItensPedido
        exclude = ['pedidos']

class PedidosForm(forms.ModelForm):
    class Meta:
        model = Pedido
        exclude = ['idCliente', 'data']

gestordepedidos/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView

# Generico

def index(request):
    num_clientes = Cliente.objects.all().count()
    num_itens = Item.objects.all().count()
    num_pedidos = Pedido.objects.all().count()
    context = {
        'num_clientes': num_clientes,
        'num_itens': num_itens,
        'num_pedidos': num_pedidos,
    }
    template_name = 'home.html'
    return render(request, template_name, context) 

# Cliente

class listaCliente(ListView):
    template_name = 'listaCliente.html'
    context_object_name = 'cliente_list'

    def get_queryset(self):
        return Cliente.objects.all()    

class detalhesCliente(DetailView):
    model = Cliente
    template_name ='detalhesCliente.html'

def cadastroCliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Cliente')
    form = ClienteForm()

    return render(request,'cadastro.html',{'form': form})

def editarCliente(request, pk, template_name='cadastro.html'):
    clientes = get_object_or_404(Cliente, pk=pk)
    form = ClienteForm(request.POST or None, instance=clientes)
    if form.is_valid():
        form.save()
        return redirect('Cliente')
    return render(request, template_name, {'form':form})    

def excluirCliente(request, pk, template_name='confirm_delete.html'):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method=='POST':
        cliente.delete()
        return redirect('Cliente')
    return render(request, template_name, {'object':cliente})

# Item

class listaItem(ListView):
    template_name = 'listaItem.html'
    context_object_name = 'item_list'

    def get_queryset(self):
        return Item.objects.all()  

def cadastroItem(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Item')
    form = ItemForm()

    return render(request,'cadastro.html',{'form': form})

def editarItem(request, pk, template_name='cadastro.html'):
    itens = get_object_or_404(Item, pk=pk)
    form = ItemForm(request.POST or None, instance=itens)
    if form.is_valid():
        form.save()
        return redirect('Item')
    return render(request, template_name, {'form':form})     

def excluirItem(request, pk, template_name='confirm_delete.html'):
    item = get_object_or_404(Item, pk=pk)
    if request.method=='POST':
        item.delete()
        return redirect('Item')
    return render(request, template_name, {'object':item})    

#Pedido

class listaPedido(ListView):
    template_name = 'listaPedido.html'
    context_object_name = 'pedido_list'

    def get_queryset(self):
        return Pedido.objects.all()   

def checkCliente(nome):
    clientes = Cliente.objects.all()

    for x in clientes:
        if x.nome == nome:
            return x.pk

    return "DONT_EXIST"

def buscaCliente(request):
    if request.method == 'POST':
        nome = request.POST["nome"]
        id_cliente = checkCliente(nome)
        if id_cliente != "DONT_EXIST":
            url = "add/" + str(id_cliente)
            return redirect(url)
        else:
            return render(request, 'clienteErro.html')
    return render(request, 'clienteBusca.html')

def cadastroPedido(request, pk):
    movimento_forms = Pedido()
    item_movimento_formset = inlineformset_factory(Pedido, ItensPedido, form=ItensPedidoForm, extra=0, can_delete=False, min_num=1, validate_min=True)

    if request.method == 'POST':
        forms = PedidosForm(request.POST, request.FILES, instance=movimento_forms, prefix='main')
        formset = item_movimento_formset(request.POST, request.FILES, instance=movimento_forms, prefix='item')

        if forms.is_valid() and formset.is_valid():
            forms = forms.save(commit=False)
            forms.idCliente = Cliente.objects.get(pk=pk)
            forms.save()
            formset.save()
            url = "../../pedido/" + str(forms.pk)
            return redirect(url)

    else:
        forms = PedidosForm(instance=movimento_forms, prefix='main')
        formset = item_movimento_formset(instance=movimento_forms, prefix='item')

    context = {
        'forms': forms,
        'formset': formset,
    }

    return render(request, 'cadastroPedido.html', context)

def detalhesPedido(request, pk):
    template_name = 'detalhesPedido.html'
    pedido = Pedido.objects.get(pk=pk)
    itensPedido = ItensPedido.objects.get_queryset().filter(pedidos=pk)
    context = {
        'movimento': pedido,
        'movimentosItens': itensPedido,
    }
    return render(request, template_name, context)                             

def excluirPedido(request, pk, template_name='confirm_delete.html'):
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.method=='POST':
        pedido.delete()
        return redirect('Pedido')
    return render(request, template_name, {'object':pedido})

gestordepedidos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!-- Google Fonts: Nunito sans -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- Reset CSS -->
    <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">

    <!-- Base CSS -->
    <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
  </head>

  <body>
    <div class="container-fluid h-100">
      <div class="row h-100">
        <div class="col-lg-2 col-md-2 col-sm-12 p-0 bg-dark">

          <ul class="nav-menu">
            <hr />
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">
                Home
              </a>
            </li>
            <hr />

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Cliente' %}">
                Clientes
              </a>
            </li>
            <hr />

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Item' %}">
                Itens
              </a>
            </li>
            <hr />

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Pedido' %}">
                Pedidos
              </a>
            </li>
            <hr />
            </ul>
        </div>

        <div class="col bg-secondary">
          <div>
            {% block content %}
            {% endblock content %}
          </div>
        </div>

      </div>
    </div>

    <!-- Boostrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"
    ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"
    ></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"
    ></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

gestordepedidos/templates/cadastro.html
{% extends 'base.html' %}
{% block content %} {% load widget_tweaks %} {% block styles %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

<div class="col">
  <div class="table-wrapper" id="round">
    <div class="table-title" id="round-top">
      <div class="row">
        <div class="col-sm-7">
          <h2>Cadastro:</h2>
          <div class="col-md-1 col-xs-1 col-sm-1"></div>
        </div>
      </div>
    </div>
    <div class="col-md-10 col-xs-10 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
          {{ field.label_tag }}
          {% render_field field class="form-control" %}
          {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
        </div>
        {% endfor %}
        <p align="right"><button type="submit" class="btn btn-success">Salvar</button></p>
      </form>
    </div>
  </div>
</div>
{% endblock %}

gestordepedidos/templates/cadastroPedido.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block content %}{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
      <script
      src="https://kit.fontawesome.com/8dcd95e926.js"
      crossorigin="anonymous"
    ></script>
{% endblock %}

<div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Realizar Pedido</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ formset.management_form }}

                    <div class="row">
                        <div class="col-sm-8">
                          <legend style="border-bottom: 1px solid #e5e5e5;">Itens</legend>
                          <div id="order" class="form-inline">
                            {% for item_form in formset %}
                              <div id="item-{{ forloop.counter0 }}" class="form-group" style="margin-top: 10px">
                                {{ item_form|bootstrap }}
                              </div>
                            {% endfor %}
                          </div>
                        </div>
                        <a class="btn pull-left" id="add-item"><i class="fa fa-plus"></i> Add Item</a>
                    </div>
                        
                    <p> 


                    </p>
                    {{ forms|bootstrap }}
                    <p> 


                    </p>
        
                    <div class="form-inline buttons">
                        <a href="{% url 'Pedido' %}" class="btn btn-warning pull-right"><i class="fa fa-times"></i> Cancelar</a>
                        <button class="btn btn-primary pull-right" value="Save"><i class="fa fa-floppy-o"></i> Salvar</button>
                    </div>
                </form>
            </div>
        </div>   
    </div> 
</div>  


         

{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(function(){
        $("#add-item").click(function(ev) {
            ev.preventDefault();
            var count = $('#order').children().length;
            var tmplMarkup = $("#item-order").html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
            $("div#order").append(compiledTmpl);

            // update form count
            $('#id_item-TOTAL_FORMS').attr('value', count + 1);

            // some animate to scroll to view our new form
            $('html, body').animate({
                scrollTop: $("#add-item").position().top-200
            }, 800);
        });
    });
</script>
<script type="text/html" id="item-order">

    <div id="item-__prefix__" class="form-group" style="margin-top: 10px">
            {{ formset.empty_form|bootstrap }}
    </div>
</script>
{% endblock scripts %}

gestordepedidos/templates/clienteBusca.html
{% extends 'base.html' %}
{% block content %}{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}
<div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Buscar Cliente:</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
        <form method="post"> {% csrf_token %}
            <div id="form_responsavel">
                <div class="form-group col-xs-12">
                    <input type="text" class="form-control" placeholder="Digite o nome do cliente" name="nome" minLength="1" required/>
                </div>
            <button type="submit" class="btn btn-success" >Buscar</button>
        </form>
    </div> 
</div>  
{% endblock %}

gestordepedidos/templates/clienteErro.html
{% extends 'base.html' %}
{% block content %}{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}
<div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div>
        <br> 
        <h3>CLIENTE NÃO CADASTRADO!!!</h3>
    </div> 
</div> 
{% endblock %}

gestordepedidos/templates/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

<div class="container">
    <div class="row"></div>
    <br />
    <div class="row">
        <div class="col-md-2 col-xs-2 col-sm-2"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning">
                        Você quer mesmo deletar {{ object }}?
                    </div>
                </div>
                {% if user.is_staff %}
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash">Sim</span>
                </button>
                {% endif %} 
            </form>
        </div>
    </div>
</div>
{% endblock %}

gestordepedidos/templates/detalhesCliente.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Cliente: #{{ cliente.pk }}</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
                    <br>
                    <p>Nome: {{ cliente.nome }}</p>
                    <p>Cpf: {{ cliente.cpf }}</p>
                    <p>Email: {{ cliente.email }}</p>
                    <br>
    </div> 
</div>  
{% endblock %}

gestordepedidos/templates/detalhesPedido.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Pedido: #{{ movimento.pk }}</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
        {% if movimento.observacao %}
        <br>
        <h5>Justificativa: </h5>
        <br>
        <p>{{ movimento.observacao }}</p>
        {% endif %}
        <table class="table table-striped table-hover table-responsive-sm text-justify">
        <thead>
          <tr>
            <th class="text-center">Descrição</th>
            <th class="text-center">Quantidade:</th>
          </tr>
        </thead>
        <tbody>
        {% for item in movimentosItens %}
                    <tr>
                      <th class="text-center">Item({{ forloop.counter }}): {{ item }}</th>
                      <th class="text-center"> {{ item.quantidade }}</th>
                    </tr>
                    <br>
        {% endfor %}
        </tbody>
      </table>
    </div> 
</div>  
{% endblock %}

gestordepedidos/templates/home.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
        <div class="row mt-3">
          <div class="col-sm-12">
            {% if user.is_authenticated %}
              <a class="btn btn-danger" href="{% url 'logout'%}"><i class="material-icons">arrow_circle_left</i> <span>Logout</span></a> <h2>Home</h2> 
            {% else %}
              <a class="btn btn-primary" href="{% url 'login'%}?next={{request.path}}"><i class="material-icons">arrow_circle_right</i> <span>Login</span></a> <h2>Home</h2> 
            {% endif %} 
          </div>
        </div>
          <div class="row">
            <div class="col-sm-7">
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
        <p> </p>
        <br>
        <ul>
          <li><strong>Clientes:</strong> {{ num_clientes }}</li>
          <li><strong>Itens:</strong> {{ num_itens }}</li>
          <li><strong>Pedidos:</strong> {{ num_pedidos }}</li>
        </ul>
    </div> 
</div>  
{% endblock %}

gestordepedidos/templates/listaCliente.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row mt-3">
            <div class="col-sm-12">
              {% if user.is_staff %}<a href="{% url 'ClienteCadastro' %}" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Adicionar novo cliente</span></a>{% endif %}  <h2>Clientes</h2> 
            </div>
          </div>
      </div>
      <table class="table table-striped table-hover table-responsive-sm text-justify">
        <thead>
            <tr>
              <th class="text-center">ID</th>
              <th class="text-center">Nome</th>
              <th class="text-center">CPF</th>
              <th class="text-center">Email</th>
              <th class="text-center">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for cliente in cliente_list %}
            <tr>
              <td class="text-center">{{ cliente.pk }}</td>
              <td class="text-center">{{ cliente.nome }}</td>
              <td class="text-center">{{ cliente.cpf }}</td>
              <td class="text-center">{{ cliente.email }}</td>
              <td class="text-center icons-td">
                {% if user.is_staff %}
                <a href="{% url 'ClienteDetalhes' cliente.pk %}" class="details">
                  <span class="material-icons">
                    visibility
                  </span>
                </a>
                <a href="{% url 'ClienteEditar' cliente.pk %}" class="edit">
                  <i class="material-icons" data-toggle="tooltip" title="Editar">&#xE254;</i>
                </a>
                <a href="{% url 'ClienteExcluir' cliente.pk %}" class="delete">
                  <i class="material-icons" data-toggle="tooltip" title="Excluir">&#xE872;</i>
                </a> 
                {% endif %}               
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>  
{% endblock %}